version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  build:
    commands:
      - dotnet restore hello-lambda.csproj
      - dotnet publish hello-lambda.csproj -c Release -o output

artifacts:
  base-directory: output
  files:
    - '**/*'
